services:
  postgres:
    image: postgres:15-alpine
    container_name: ciphersql_sandbox
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ciphersql_sandbox
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
